src/index.js, src/js/api-service.js, src/js/refs.js, src/js/templates/render-card-modal.js, src/partials/components/card-modal.html
при викликі фонкції renderModal :
-на refs.backdrop додається значення movieId яке є аргументом функціі
-запит інформації про Фільм за його ID (appService.fetchMovieDetails)
-створення розмітки  (createModalMarkup)
-.додання розмітки в DOM за допомогою  (uppendModalMarkap)
function openModal
знімає is.hidden з refs.backdrop та додає слухачів
function closeModal
додає is.hidden на refs.backdrop та знімає слухачів
реалізовано:
-закриття по Esc
-закриття по кнопкі або по кліку на бєкдроп
=> FT-17:додав функції для рендеру та закриття модалки

src/index.js, src/js/templates/render-footer.js, src/partials/footer.html
Добавив розмітку футера у функцію і експортнув її у index.js
=> add renderFooter function

src/sass/layout/_gallery.scss
Випривив синтаксичну помилку в scss
=> fixed syntax-error-gallery

src/js/handlers/localStorageOptions.js, src/js/localStorageApi.js, src/js/renderModalCard.js, src/js/templates/modalCardMarkap.js, src/sass/components/_card-modal.scss
Прив'язав логіку з localStorageApi до кнопок модального вікна
при натисканні на кнопку Add toWatch /Add to Queue:
- фільм додається у відповідний массив localStorage 
-текст на кнопках звінюється відповідно Delete to Watch /Delete to Queue
-додається клас isActive (для зміни кольору)
-сусідьня кнопка отримує disabled
При повторному натисканні "зеркальна логіка"
При рендері модалки кнопки пиймають стилі відповідно до данних з localStorage
=> feature/FT-18/FT-19 add lockalStorage options

src/js/localStorageApi.js
=> bugfix FT-28: added blocks try/catch to launching JSON.parse

src/js/handlers/onSearchMovie.js, src/js/templates/render-popular-card.js
add usage search in onSearchMovie.js, add const poster_url in render-popular-card.js
=> FT-33:  add usage input-keyword search,

src/js/showFailMessage.js, src/js/templates/header/createHeaderHomeMarkup.js, src/js/templates/header/createHeaderLibraryMarkup.js, src/js/templates/header/createInitialHeaderMarkup.js, src/sass/layout/_header.scss
1. Исправил header
2. Исправил исчезновение уведомления
=> FT-01: fixed header bg | FT-31: fixed message hide

src/index.js, src/js/createPaginationBtn.js, src/js/handlers/handlerResponse.js, src/js/handlers/onSearchMovie.js, src/js/templates/header/renderHomeHeader.js, src/js/templates/render-popular-card.js
1. Корректная пагинация при поиске.
2. при клике на кнопку Ноme рендерятся тренды.
=> FT-34: correct pagination search btn

src/js/api-service.js, src/js/handlers/localStorageOptions.js, src/js/handlers/modalCardOptions.js, src/js/handlers/onPlayBtnClick.js, src/js/renderModalCard.js, src/js/templates/modalCardMarkap.js, src/sass/components/_card-modal.scss
змінив розмітку модального вікна(з інформацією про фільм)
додав до розмітки елемент iframe  з посиланням на трейлер данного фільму в youtube
додав кнопку play яка відкриває трейлер
додав кнопку close treiler яка закриває трейлер
додав функції які реалізують відкриття/закриття трейлера
=> FT-41 add trailer in modal card

src/js/handlers/handlerResponse.js, src/js/handlers/onSearchMovie.js, src/js/showFailMessage.js, src/sass/layout/_header.scss
1. Добавил уведомления при пустом инпуте и неудачном поиске
2. Подправил стили header
=> FT-39: added notifications for noresult and empty input

src/js/createPaginationBtn.js, src/js/templates/paginationMarkup.js, src/js/templates/render-basic-gallery.js, src/sass/layout/_gallery.scss
1. Переписал заново логику создания разметки кнопок пагинации.
2. Исправил ошибку при нажатии на `...`
=> FT-26: improved button rendering logic

src/js/handlers/teamModalOptions.js, src/sass/components/_team-madal.scss
Анимировала модалку. Если слишком - скажи)
=> add animation to team modal

src/sass/components/_spiner.scss
=> bugfix FT-52 add spiner transition

src/sass/components/_card-modal.scss
--додав width 100% при фіксації контенту при відкритті модалки
=> fixed scroll

src/js/handlers/modalCardOptions.js, src/sass/components/_card-modal.scss
-змінив налаштування noScroll
-додав   overflow: auto; на випадок переповнення текстом блоку about text.
=> fixed noScroll, fixed modal__about-text

src/js/templates/header/createHeaderHomeMarkup.js, src/js/templates/header/createInitialHeaderMarkup.js, src/sass/utils/_base-styles.scss
1. отключил autocomplete
2. пофиксил прыгающую разметку
=> FT-57: fixed input | FT-51: fixed jumping markup

src/js/templates/render-basic-gallery.js, src/sass/layout/_gallery.scss
Поправив стилі фільтру, забрав скроллбар.
=> FT-48 remuve filter scrollbar

src/js/firebase.js, src/js/handlers/onLibraryLinkClick.js, src/js/templates/header/createAuthMarkup.js, src/sass/layout/_header.scss
При натисканні кнопки library, якщо користувач не авторизований, його перенаправляє на сторінку авторизації
=> add Auth to onLibraryBtn

src/js/handlers/modalCardOptions.js, src/js/templates/modalCardMarkap.js, src/sass/components/_card-modal.scss
-виправив позиціювання елементів
=> fixed size textContent in about in modal card

src/js/createPaginationBtn.js, src/js/handlers/handlerResponse.js, src/js/spiner.js, src/js/templates/renderQueueList.js, src/js/templates/renderWatchedList.js
1. Добавил спинер на кнопки пред-след
2. Добавил автовыключение спинера на 500ms
=> FT-67: fixed spiner on prev-next btns, added auto-off in 500ms

src/js/templates/renderQueueList.js, src/js/templates/renderWatchedList.js
1. Убрал пагинацию в пустой библиотеке
=> FT-66: hid pagination in empty library

src/sass/components/_team-madal.scss
Изменила марджины, паддинги, шрифт.
Изменила анимацию
=> change animation, change margin, padding and fond

src/js/handlers/onLibraryLinkClick.js, src/js/renderLibraryPagination.js, src/js/templates/renderQueueList.js, src/js/templates/renderWatchedList.js
1. убрал пагинацию в библиотеке если только одна страница
2. подправил спинер, + вкл ри нажатии на Watched и Queue
=> FT-68: fixed pagination only 1 page and fixed spiner on library

src/js/templates/render-basic-gallery.js, src/sass/layout/_gallery.scss
=> FT-69 fix filter styles

src/js/handlers/onLibraryLinkClick.js, src/js/renderLibraryPagination.js, src/js/templates/renderQueueList.js, src/js/templates/renderWatchedList.js
Reverts Vitalii-Khivrych/team-project-filmoteka#107
=> Revert "FT-68: fixed pagination only 1 page and fixed spiner on library"

src/js/handlers/onLibraryLinkClick.js, src/js/renderLibraryPagination.js, src/js/templates/renderQueueList.js, src/js/templates/renderWatchedList.js
Reverts Vitalii-Khivrych/team-project-filmoteka#108
=> Revert "Revert "FT-68: fixed pagination only 1 page and fixed spiner on library""

src/index.js, src/js/scrollUp.js, src/js/templates/render-basic-gallery.js, src/sass/layout/_gallery.scss
=> Revert "Feature/ft  59"

src/index.js, src/js/scrollUp.js, src/js/templates/render-basic-gallery.js, src/sass/layout/_gallery.scss
Reverts Vitalii-Khivrych/team-project-filmoteka#110
=> Revert "Revert "Feature/ft  59""

src/js/handlers/onPlayBtnClick.js, src/js/renderModalCard.js
змінив логіку ренлеру розмітки трейлера:
- при рендері модалки іде запит за ключем ртейлера
- по його результату при наявності трейлера відображується кнопка плей і їй привласнюється ID зі значенням ключа трейлера в іншому випадку кнопка не з'являється
- при натисканні на кнопку плей створюється розмітка трейлера і відтворюється в модальному вікні
=> change logic from render trailer markup

src/js/templates/paginationMarkup.js
Пагінація не з'являється якщо прийшла лише одна сторінка
=> FT-73: dont create pagination if total page 1

src/index.js, src/js/createSearchFilter.js, src/js/handlers/onSearchFilters.js, src/js/handlers/onSearchMovie.js, src/js/initRenderTrendingMovie.js, src/js/service/chengingUrlApi.js, src/js/templates/header/renderHomeHeader.js
1. Строка фільтру не зникає при поверненні з бібліотеки.
2. Фільтр не зникає при пошуку.
3. Значення фільтру зберігається при поверненні з бібліотеки.
=> FT-75: filter dont delet for searcj or wwent from libary

src/js/handlers/handlerResponse.js, src/js/showSuccessMessage.js, src/sass/layout/_header.scss
1. Добавил уведомление при успешном поиске
=> FT-84: added success notification

src/sass/layout/_header.scss
=> FT-88: fixed input styles

src/js/handlers/onPlayBtnClick.js, src/js/templates/traillerMarkup.js, src/sass/components/_card-modal.scss
-виправив закриття увімкненого плеєра для desktop-ної версії сайта
=> fixed keydown esc on close trailer
